### ISSUE TITLE
Why the results are different?

### ISSUE THREAD

**Issue by yingjieyao** [votchallenge/toolkit-legacy#121]
Sorry to bother but I don't know why the results of VOT2015 I get are **not consistent** with the [`VOT2015 Results`](http://data.votchallenge.net/vot2015/presentations/vot_2015_paper.pdf).
I download the VOT2015 results from [`the official site`](http://votchallenge.net/vot2015/results.html) and run the toolkit to generate the report, but happen to find the result I get is not consistent with the paper states.
My toolkit version is `major 4, minor 1`. 

Another finding is that all my results are consistent with some papers, such as [`SiameseFC`](https://arxiv.org/pdf/1606.09549.pdf).

Anything else I need to do to generate the VOT2015 report?

For example, the MDNet, EBT, DeepSRDCF and SRDCF's results all seem lower the than the results in the vot2015 paper  with respect to accuracy.

**Comment by lukacu** [comment]
Sorry for late reply, I somehow missed this issue. Can you provide an example of a difference (what is its scale)? One of the reasons for small differences may be that we are constantly changing the toolkit which unfortunately also introduces some changes in analysis. To completely reproduce the results you may then try to use the same toolkit that was used for that challenge (in your case something like 3.1), but since we do not provide builds for older version you may have to compile it yourself.

**Comment by gongbudaizhe** [comment]
I have encountered similar issues #148 

For example, the non-realtime Accuracy of KCF is 0.4339 but the reported value is 0.447. Robustness and EAO is the same though. I have also tried the SiamFC tracker, the Accuracy is consistently lower than the reported value in VOT17.
