### ISSUE TITLE
How to make vot-toolkit support c++11

### ISSUE THREAD

**Issue by he010103** [votchallenge/toolkit-legacy#173]
Hi @bjanssen ， I use the python interface of vot-toolkit. When using PyTorch 0.4.0，error occurred. 
TRAX_BOUNDED_OVERLAP: true
TRAX_REGION_LEGACY: false
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hezhiqun/environment/pytorch/examples/CRT/vot/python_siamfc.py", line 9, in <module>
    import torch
  File "/home/hezhiqun/share/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
RuntimeError: stoi
Error: Tracker exited with exit code 1

I use `tracker_interpreter = '/home/hezhiqun/anaconda3/bin/python';` to enable torch.

I think maybe toolkit can not support C++11. How can I solve this problem. Thanks!

**Comment by alanlukezic** [comment]
Which operating system (and version) are you using?

**Comment by he010103** [comment]
I am using CentOS Linux release 7.2.1511 (Core)
Linux version 3.10.0-514.16.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) )

**Comment by alanlukezic** [comment]
Similar errors has already happened before when using very recent versions of the Matlab and Linux. The problem seemed to be in the non-compatible libraries the system and Matlab are using. Try to force it to use the system libraries instead of using Matlab libraries (you can just rename the problematic libraries located in matlab sub-folders).

**Comment by alanlukezic** [comment]
Hi, I think that the problem is not in the interpreter, but in libraries included by the toolkit.

**Comment by leeyeehoo** [comment]
Well, the solution is to degrade the PyTorch to 0.3.x or 0.2.x.

**Comment by leeyeehoo** [comment]
@mozhuangb Seems no other way except degrading pytorch.

**Comment by juanitoroter** [comment]
Also I reproduce the same error when just run system(['source activate Py36Torch; python -c "import torch"']) from Matlab2016a and Matlab2018a. Even if I force to Matab to use my system libraries or my Python environment libraries: LD_PRELOAD=~/.conda/envs/Py36Torch/lib/libstdc++.so.6 /home2/Softwares/MATLAB/R2016b/bin/matlab

It is really a pity if the only solution is just degrading pytorch (it is not possible for me!)

**Comment by fzh0917** [comment]
Actually, I think that the reason why these problems and errors occur is that the toolkit is written by `Matlab`. So if anyone reimplement it using `Python` or `C++`, I will be the first one to sponsor it.

**Comment by lukacu** [comment]
We are considering switching to Python for some time now, but the problem is lack of people to do the coding. If somebody is interested in helping, please write me an email, I will see what can be organized as the toolkit was always considered an open-source project.

Tthe idea of the toolkit is that it is modular in terms of tracker support (via TraX protocol) so that all existing trackers can run instantly in Python or any other environment.

Regarding the issue at hand, I have some time now and I can look at the problem, but I would need to reproduce the problem. Is the tracker used available for download?

**Comment by lawpdas** [comment]
reference https://github.com/pytorch/pytorch/issues/7082#issuecomment-431875565
I solve this by changing
https://github.com/votchallenge/vot-toolkit/blob/c03b406734c0bcd33f7a3c2fb9519b8b07dbb83f/tracker/generate_python_command.m#L63
to
`command = sprintf('env -i %s %s -c "%s"', python_executable, argument_string, python_script);`

**Comment by lukacu** [comment]
Hey, thanks for pointing it out, we will investigate if we can integrate your solution into the toolkit.

**Comment by lawpdas** [comment]
There are still many problems for running a pytorch tracker or a tensorflow tracker with trax, even if the tracker can be run without any problem in the terminal, especially when the tracker needs an anaconda environment.
In the terminal, I need to switch to an anaconda environment before runnig the tracker. In the toolkit, traxclient can execute the python command to run the tracker.  But it seems that traxclient couldn't find some libraries of anaconda environment, even though the anaconda library directory has been added to the `tracker_linkpath`.
So how to switch environment before executing the python command? Can I switch to an anaconda environment with `conda activate` comand using traxclient?

**Comment by lukacu** [comment]
Well, the `tracker_linkpath` will try to set paths using environmental variables, but since your are cleaning up the environment with `env` command this will not work. I guess it would be better to determine which Matlab envvars are causing problems, but you can also hack the command to set the path manually, we just cannot get this into the toolkit as it is not a general and cross-platform solution.

**Comment by ShuaiBai623** [comment]
I solve this new problem by adding `setenv('MKL_NUM_THREADS','1')` in the tracker configure file.
