### ISSUE TITLE
RGBT break sometime when restart after lost

### ISSUE THREAD

**Issue by JudasDie** [votchallenge/toolkit-legacy#235]
Hello~
I met a problem about RGBT running. When the tracker lost target, the log print the following information:
```
@@TRAX:quit 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/home/v-zhipeng/project/codes2/vot-python/vot-toolkit/tracker/examples/python/AASRGBT/pytracking/pytracking/python_aas.py", line 56, in <module>
    colorimage_file, infimage_file = handle.frame()
TypeError: 'NoneType' object is not iterable
@@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=polygon;" "trax.description=" "trax.version=2" "trax.channels=color;ir;" 
@@TRAX:initialize "file:///data/home/v-zhipeng/project/codes2/vot-python/vot-toolkit/vot-workspace2019RGBT/sequences/balancebike/color/00143v.jpg" "file:///data/home/v-zhipeng/project/codes2/vot-python/vot-toolkit/vot-workspace2019RGBT/sequences/balancebi
@@TRAX:state "350.0000,110.0000,375.0000,110.0000,375.0000,182.0000,350.0000,182.0000" 
```

Toolkit break sometime after this. And sometime not. When re-run `run_experiment.m`, toolkit can run normally again.  However there is no wrong information in log file. When I compare this to log information in short-term tracking challenge, 'Nonetype' will not show in log file of short-term  tracking when tracker lost target. Is there any problem with RGBT data generation?

**Comment by lukacu** [comment]
From the short fragment that you have provided I can assume that there was a problem retrieving a new frame, the result of handle.frame() is None and therefore cannot be unpacked into two images. Why this happened is not clear from the data and it could be handled better, but is unfortunately not so you have to provide an additional check. But the underlying problem is likely something else, considering that it is a stochastic issue it is likely in your tracker.

**Comment by Alexadlu** [comment]
Hi, Have you solved your problem? I have the same problem.@JudasDie
